spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    
    
# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.**.mapper
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
    - classpath:mapper/*.xml
#日志
#logging:
#  level:
#    com.business: DEBUG    
